config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post "/login" => "sessions#create", as: "login"
  get "/login" => "sessions#new"
  delete "/logout" => "sessions#destroy", as: "logout"

  get "/user_doc" => "users#doc", as: "doc"

  resources :users, only: [:new, :create]

  resources :tasks 

  patch "/timeentries/:id/start_timer" => "timeentries#start_timer", as: "start_timer"

  patch "/timeentries/:id/stop_timer" => "timeentries#stop_timer", as: "stop_timer"

  resources :timeentries

  resources :customers do 
    resources :projects do
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :customer
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_one :timeentry
	belongs_to :project
end

app/models/timeentry.rb
class Timeentry < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :task

  def self.total(array)
  	a = []
  	array.each{ |x| a << x.duration } 
  	a.inject{|sum,x| sum += x }
  end

  def self.to_csv(options = {}) 
  	# headers = ["Task","Project","Notes","Duration"]
  	CSV.generate do |csv|
  		csv << column_names
  		all.each do |te|
  			csv << te.attributes.values_at(*column_names)
  		end
  	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :timeentries

	attr_reader :entered_password

	validates :username, presence: true, length: { minimum: 3 }
	validates :email, presence: true, uniqueness: true, format: /.+@.+\..+/
	validates :entered_password, presence: true, length: { minimum: 6 }
	validates :password, confirmation: true
	validates :password_confirmation, presence: true
	
	def password
		@password ||= BCrypt::Password.new(password_hash)
	end

	def password=(new_password)
		@entered_password = new_password
		@password = BCrypt::Password.create(new_password)
		self.password_hash = @password
	end

	def self.authenticate(email, password)
		user = User.find_by_email(email)
		return user if user && (user.password == password)
		nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :current_user, :logged_in?

  protect_from_forgery with: :exception

  def current_user
  	@user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!(session[:user_id].nil?)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		@customers = Customer.all
	end

	def show
		@c = Customer.find(params[:id])
		@p = @c.projects
		te = []
		@p.each do |x|
			te << Timeentry.where(project_id: x.id)
		end
		@tes = te[0]
		respond_to do |format|
			format.html
			format.xls { send_data @tes.to_csv(col_sep: "\t") }
		end
	end

	def new
		@c = Customer.new
	end

	def create
		@c = Customer.new(customer_params)
		@c.save
		redirect_to customers_path
	end

	private
	def customer_params
		params.require(:customer).permit(:company)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@c = Customer.find(params[:customer_id])
		@p = Project.new
	end

	def create
		@p = Project.new(project_params)
		@p.customer_id = params[:customer_id]
		@p.save

		redirect_to customer_path(@p.customer)
	end

	private
	def project_params
		params.require(:project).permit(:project_name)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		if logged_in?
			redirect_to root_path
		else
			@session = nil
		end		
	end

	def create
		user = User.authenticate(params[:user_email], params[:user_password])
		if user
			session[:user_id] = user.id
			redirect_to timeentries_path
		else
			flash[:error] = "Invalid email or password"
			render 'new'
		end
	end

	def destroy
		session.clear
		redirect_to root_path
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def index
		@tasks = Task.all		
	end

	def new
		@t = Task.new
	end

	def create
		@t = Task.new(task_params)
		@t.save
		redirect_to tasks_path
	end

	private
	def task_params
		params.require(:task).permit(:task_name,:project_id)
	end
end

app/controllers/timeentries_controller.rb
class TimeentriesController < ApplicationController
	def index
		@timee = Timeentry.where(user_id: current_user.id)	
		@t = Timeentry.total(@timee)
		respond_to do |format|
			format.html
			format.csv { send_data @timee.to_csv}
			format.xls { send_data @timee.to_csv(col_sep: "\t") }
		end
	end

	def new
		@timeentry = Timeentry.new
	end

	def edit
		@timee = Timeentry.find(params[:id])
		if @timee.start_time == nil
			render 'edit'
		else
			@t = Timeentry.new
			@d = Time.now - (@timee.start_time)
		end
	end

	def create
		@timeentry = Timeentry.new(timeentry_params)

		@timeentry.user_id = current_user.id
		
		@timeentry.save
		redirect_to timeentries_path
	end

	def update
		@timee = Timeentry.find(params[:id])
		@timee.duration = @timee.duration + (params[:timeentry][:start_time]).to_f
		@timee.save
		redirect_to timeentries_path
	end

	def start_timer
		timee = Timeentry.find(params[:id])
		timee.start_time = Time.now
		timee.save!

		redirect_to timeentries_path
	end

	def stop_timer
		timee = Timeentry.find(params[:id])

		if timee.duration == nil
			timee.duration = Time.now - (timee.start_time)
		else
			timee.duration = timee.duration + (Time.now - (timee.start_time))
		end

		timee.start_time = 0
		timee.save
		redirect_to timeentries_path
	end


	private
	def timeentry_params
		params.require(:timeentry).permit(:note, :project_id, :task_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to timeentries_path
		else
			render 'new'
		end
	end

	def doc
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def redirect_if_logged_in
		redirect_to root_path if logged_in?
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/timeentries_helper.rb
module TimeentriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/index.html.erb
<h1>Customer Index</h1>
<%= link_to 'New Customer', new_customer_path %>
<br>


<% @customers.each do |c| %>
<ul>
	<li><%= link_to c.company, customer_path(c) %> </li>
</ul>
<% end %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= form_for @c do |f| %>

<p>
	<%= f.text_field :company, placeholder: 'company' %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

app/views/customers/show.html.erb
<h1><%= @c.company %></h1>
<h5>info:</h5>

<hr>
<h6>Projects</h6>

<%= link_to 'New Project', new_customer_project_path(@c) %>
<% @p.each do |x| %>
<ul>
	<li><%= x.project_name  %></li>
</ul>
<% end %>

<hr>
<h6>Timeentries Report</h6>

<table>
	<tr>
		<th>Id</th>
		<th>Task</th>
		<th>Project</th>
		<th>Duration</th>
	</tr>
<% @tes.each do |t| %>
	<tr>
		<td><%= t.id %></td>
		<td><%= t.task.task_name %></td>
		<td><%= t.project.project_name %></td>
		<td><%= t.duration %></td>
	</tr>
<% end %>
</table>

<p>
	Download: 
	<%= link_to 'Excel', customer_path(format: 'xls') %>
</p>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for ([@c, @c.projects.build]) do |f| %>

<%= f.text_field :project_name, placeholder: 'project name' %>

<p>
	<%= f.submit %>
</p>

<% end %>

app/views/tasks/index.html.erb
<h1>Tasks Index</h1>

<%= link_to 'New Task', new_task_path %>

<ul>
<% @tasks.each do |t| %>
	<li><%= t.task_name %></li>
<% end %>
</ul>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for @t do |f| %>

	<p>
		<%= f.collection_select(:project_id, Project.all, :id, :project_name) %>
	</p>
	
	<p>
		<%= f.text_field :task_name, placeholder: 'task name' %>
	</p>

	<p>	
		<%= f.submit %>
	</p>
<% end %>

app/views/timeentries/edit.html.erb
<h1>Edit Timeentry</h1>

<h3>Duration so far: <%= @d %></h3>

<%= link_to 'Stop Timer', stop_timer_path, :method => :patch %>

<%= form_for @timee do |f| %>

	<p>
		Manually enter time:
	</p>
	<p>
		<%= f.text_field :start_time, placeholder: 'duration' %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/timeentries/index.html.erb
<h1>Timeentry Index</h1>

<h2><%=  (Time.now).strftime("%A, %b %d")%></h2>

<%= link_to 'New Entry', new_timeentry_path %>

<table>
	<% @timee.each do |t| %>
	<tr>
		<td><%= t.task.task_name %> (<%= t.project.project_name %>)  </td>
	</tr>
	<tr>
		<td><%= t.note %></td>
		<td><%= t.duration %></td>
		<td><%= link_to 'Start', start_timer_path(t), :method => :patch %></td>
		<td><%= link_to 'Edit', edit_timeentry_path(t) %></td>
	</tr>
	<% end %>
	<tr>
		<td></td>
		<td>Total: <%= @t %></td>
	</tr>
</table>

<p>
	Download:
	<%= link_to 'CSV', timeentries_path(format: 'csv') %> |
	<%= link_to 'Excel', timeentries_path(format: 'xls') %>
</p>

app/views/timeentries/new.html.erb
<h1>New TimeEntry</h1>

<%= form_for @timeentry do |f| %>
	

	<p>Project:
		<%= f.collection_select(:project_id, Project.all, :id, :project_name) %>
	</p>

	<p>Task:
		<%= f.collection_select(:task_id, Task.all, :id, :task_name) %>
	</p>

	<p>
		<%= f.text_area :note, placeholder: 'note' %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/users/doc.html.erb
<h2>User Documentation</h2>

<h4>Time Tracker</h4>

<p>This app gives the user the ability to easily and coveniently enter their projects hours any time, day or night and for the home office to be able to produce up-to date reports 24-7. Customers are already loaded into database so you can create projects for customers and link them to time entries. The User has an individual login for security purposes.</p>

<h4>Capabilities</h4>

<ul>
	<li>employee login</li>
	<li>log when work was done (date and time)</li>
	<li>link customer to project adn time entry</li>
	<li>record the user who worked on the project</li>
	<li>record how long the task took</li>
	<li>record notes for time entries</li>
	<li>manually enter in hours for tasks</li>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<div class="wrap-center">
	<% if @user.errors.any? %>
		<%= pluralize(@user.errors.count, "error") %>
		prohibited user from being created:
		<% @user.errors.full_messages.each do |msg| %>
			<ul>
				<li><%= msg %></li>
			</ul>
		<% end %>
	<% end %>

	<%= form_for @user do |f| %>

	<p>
		<%= f.text_field :username, placeholder: 'name' %>
	</p>

	<p>
		<%= f.text_field :email, placeholder: 'email' %>
	</p>

	<p>
		<%= f.password_field :password, placeholder: 'password' %>
	</p>

	<p>
		<%= f.password_field :password_confirmation, placeholder: 'password confirmation' %>
	</p>


	<%= f.submit 'Sign Up' %>

	<% end %>

</div>

app/views/welcome/index.html.erb
<h1>Welcome to Track the Time Homey</h1>
<p>
	<%= link_to 'User Documentation', doc_path %>
</p>

<%= link_to 'Customers', customers_path %>

<%= link_to 'Timeentries', timeentries_path %>

<%= link_to 'Tasks', tasks_path %>